---
- name: Docker
  hosts: all
  become: true
  tasks:
   - name: Update Cache
     apt:
       update_cache: yes
   - name: Docker Installation
     apt:
        name: docker.io
        state: present
   - name: Enable docker
     service:
        name: docker
        state: started
        enabled: true
   - name: pulling the image from Dockerhub
     command: docker pull sridevi4/capstone:1.0
   - name: run my image as docker
     command : docker run --name python -d -p 80:80 --restart=always sridevi4/capstone:1.0
